//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.1.0 (NJsonSchema v11.5.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IApiClient {

    /**
     * @param limit (optional) 
     * @return Success
     */
    cardsAll(limit: number | undefined, signal?: AbortSignal): Promise<Card[]>;

    /**
     * @param body (optional) 
     * @return Success
     */
    cardsPOST(body: CardCreateDto | undefined, signal?: AbortSignal): Promise<Card>;

    /**
     * @return Success
     */
    cardsGET(id: string, signal?: AbortSignal): Promise<Card>;

    /**
     * @param body (optional) 
     * @return Success
     */
    cardsPUT(id: string, body: CardUpdateDto | undefined, signal?: AbortSignal): Promise<Card>;

    /**
     * @return Success
     */
    cardsDELETE(id: string, signal?: AbortSignal): Promise<void>;

    /**
     * @return Success
     */
    decksAll(signal?: AbortSignal): Promise<Deck[]>;

    /**
     * @param body (optional) 
     * @return Success
     */
    decksPOST(body: DeckCreateDto | undefined, signal?: AbortSignal): Promise<Deck>;

    /**
     * @return Success
     */
    decksGET(id: number, signal?: AbortSignal): Promise<Deck>;

    /**
     * @param body (optional) 
     * @return Success
     */
    decksPUT(id: number, body: DeckUpdateDto | undefined, signal?: AbortSignal): Promise<Deck>;

    /**
     * @return Success
     */
    decksDELETE(id: number, signal?: AbortSignal): Promise<void>;

    /**
     * @return Success
     */
    handEvalsAll(signal?: AbortSignal): Promise<HandEval[]>;

    /**
     * @param body (optional) 
     * @return Success
     */
    handEvalsPOST(body: HandEvalCreateDto | undefined, signal?: AbortSignal): Promise<HandEval>;

    /**
     * @return Success
     */
    handEvalsGET(id: number, signal?: AbortSignal): Promise<HandEval>;

    /**
     * @return Success
     */
    handEvalsDELETE(id: number, signal?: AbortSignal): Promise<void>;

    /**
     * @return Success
     */
    handsAll(signal?: AbortSignal): Promise<Hand[]>;

    /**
     * @param body (optional) 
     * @return Success
     */
    handsPOST(body: HandCreateDto | undefined, signal?: AbortSignal): Promise<Hand>;

    /**
     * @return Success
     */
    handsGET(id: number, signal?: AbortSignal): Promise<Hand>;

    /**
     * @return Success
     */
    handsDELETE(id: number, signal?: AbortSignal): Promise<void>;

    /**
     * @return Success
     */
    scryfall(signal?: AbortSignal): Promise<ImportResult>;

    /**
     * @return Success
     */
    status(signal?: AbortSignal): Promise<void>;

    /**
     * @return OK
     */
    healthCheck(signal?: AbortSignal): Promise<string>;

    /**
     * @return OK
     */
    hello(signal?: AbortSignal): Promise<string>;
}

export class ApiClient implements IApiClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = this.getBaseUrl("", baseUrl);
    }

    /**
     * @param limit (optional) 
     * @return Success
     */
    cardsAll(limit: number | undefined, signal?: AbortSignal): Promise<Card[]> {
        let url_ = this.baseUrl + "/api/Cards?";
        if (limit === null)
            throw new globalThis.Error("The parameter 'limit' cannot be null.");
        else if (limit !== undefined)
            url_ += "limit=" + encodeURIComponent("" + limit) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCardsAll(_response);
        });
    }

    protected processCardsAll(response: Response): Promise<Card[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Card[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Card[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    cardsPOST(body: CardCreateDto | undefined, signal?: AbortSignal): Promise<Card> {
        let url_ = this.baseUrl + "/api/Cards";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCardsPOST(_response);
        });
    }

    protected processCardsPOST(response: Response): Promise<Card> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Card;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Card>(null as any);
    }

    /**
     * @return Success
     */
    cardsGET(id: string, signal?: AbortSignal): Promise<Card> {
        let url_ = this.baseUrl + "/api/Cards/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCardsGET(_response);
        });
    }

    protected processCardsGET(response: Response): Promise<Card> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Card;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Card>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    cardsPUT(id: string, body: CardUpdateDto | undefined, signal?: AbortSignal): Promise<Card> {
        let url_ = this.baseUrl + "/api/Cards/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCardsPUT(_response);
        });
    }

    protected processCardsPUT(response: Response): Promise<Card> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Card;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Card>(null as any);
    }

    /**
     * @return Success
     */
    cardsDELETE(id: string, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/Cards/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCardsDELETE(_response);
        });
    }

    protected processCardsDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Success
     */
    decksAll(signal?: AbortSignal): Promise<Deck[]> {
        let url_ = this.baseUrl + "/api/Decks";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDecksAll(_response);
        });
    }

    protected processDecksAll(response: Response): Promise<Deck[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Deck[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Deck[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    decksPOST(body: DeckCreateDto | undefined, signal?: AbortSignal): Promise<Deck> {
        let url_ = this.baseUrl + "/api/Decks";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDecksPOST(_response);
        });
    }

    protected processDecksPOST(response: Response): Promise<Deck> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Deck;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Deck>(null as any);
    }

    /**
     * @return Success
     */
    decksGET(id: number, signal?: AbortSignal): Promise<Deck> {
        let url_ = this.baseUrl + "/api/Decks/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDecksGET(_response);
        });
    }

    protected processDecksGET(response: Response): Promise<Deck> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Deck;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Deck>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    decksPUT(id: number, body: DeckUpdateDto | undefined, signal?: AbortSignal): Promise<Deck> {
        let url_ = this.baseUrl + "/api/Decks/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDecksPUT(_response);
        });
    }

    protected processDecksPUT(response: Response): Promise<Deck> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Deck;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Deck>(null as any);
    }

    /**
     * @return Success
     */
    decksDELETE(id: number, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/Decks/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDecksDELETE(_response);
        });
    }

    protected processDecksDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Success
     */
    handEvalsAll(signal?: AbortSignal): Promise<HandEval[]> {
        let url_ = this.baseUrl + "/api/HandEvals";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHandEvalsAll(_response);
        });
    }

    protected processHandEvalsAll(response: Response): Promise<HandEval[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HandEval[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<HandEval[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    handEvalsPOST(body: HandEvalCreateDto | undefined, signal?: AbortSignal): Promise<HandEval> {
        let url_ = this.baseUrl + "/api/HandEvals";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHandEvalsPOST(_response);
        });
    }

    protected processHandEvalsPOST(response: Response): Promise<HandEval> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HandEval;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<HandEval>(null as any);
    }

    /**
     * @return Success
     */
    handEvalsGET(id: number, signal?: AbortSignal): Promise<HandEval> {
        let url_ = this.baseUrl + "/api/HandEvals/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHandEvalsGET(_response);
        });
    }

    protected processHandEvalsGET(response: Response): Promise<HandEval> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HandEval;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<HandEval>(null as any);
    }

    /**
     * @return Success
     */
    handEvalsDELETE(id: number, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/HandEvals/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHandEvalsDELETE(_response);
        });
    }

    protected processHandEvalsDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Success
     */
    handsAll(signal?: AbortSignal): Promise<Hand[]> {
        let url_ = this.baseUrl + "/api/Hands";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHandsAll(_response);
        });
    }

    protected processHandsAll(response: Response): Promise<Hand[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Hand[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Hand[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    handsPOST(body: HandCreateDto | undefined, signal?: AbortSignal): Promise<Hand> {
        let url_ = this.baseUrl + "/api/Hands";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHandsPOST(_response);
        });
    }

    protected processHandsPOST(response: Response): Promise<Hand> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Hand;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Hand>(null as any);
    }

    /**
     * @return Success
     */
    handsGET(id: number, signal?: AbortSignal): Promise<Hand> {
        let url_ = this.baseUrl + "/api/Hands/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHandsGET(_response);
        });
    }

    protected processHandsGET(response: Response): Promise<Hand> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Hand;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Hand>(null as any);
    }

    /**
     * @return Success
     */
    handsDELETE(id: number, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/Hands/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHandsDELETE(_response);
        });
    }

    protected processHandsDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Success
     */
    scryfall(signal?: AbortSignal): Promise<ImportResult> {
        let url_ = this.baseUrl + "/api/Import/scryfall";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processScryfall(_response);
        });
    }

    protected processScryfall(response: Response): Promise<ImportResult> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ImportResult;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ImportResult>(null as any);
    }

    /**
     * @return Success
     */
    status(signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/Import/status";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStatus(_response);
        });
    }

    protected processStatus(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    healthCheck(signal?: AbortSignal): Promise<string> {
        let url_ = this.baseUrl + "/health";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHealthCheck(_response);
        });
    }

    protected processHealthCheck(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : _responseText as string;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * @return OK
     */
    hello(signal?: AbortSignal): Promise<string> {
        let url_ = this.baseUrl + "/";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processHello(_response);
        });
    }

    protected processHello(response: Response): Promise<string> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : _responseText as string;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string>(null as any);
    }
}

export interface Card {
    id?: string;
    name?: string | null;
    mana_cost?: string | null;
    oracle_text?: string | null;
    type?: string | null;
    power_toughness?: string | null;
    cmc?: number;
    colors?: string[] | null;
    created_at?: string;
    updated_at?: string;
    deck_cards?: DeckCard[] | null;
    card_index?: CardIndex;
}

export interface CardCreateDto {
    name?: string | null;
    mana_cost?: string | null;
    type?: string | null;
    oracle_text?: string | null;
    cmc?: number | null;
}

export interface CardIndex {
    id?: number;
    card_id?: string;
    created_at?: string;
    card?: Card;
}

export interface CardUpdateDto {
    name?: string | null;
    mana_cost?: string | null;
    type?: string | null;
    oracle_text?: string | null;
    cmc?: number | null;
}

export interface Deck {
    id?: number;
    name?: string | null;
    format?: string | null;
    owner?: string | null;
    created_at?: string;
    updated_at?: string;
    deck_cards?: DeckCard[] | null;
}

export interface DeckCard {
    deck_id?: number;
    card_id?: string;
    count?: number;
    created_at?: string;
    deck?: Deck;
    card?: Card;
}

export interface DeckCreateDto {
    name?: string | null;
    format?: string | null;
    owner?: string | null;
}

export interface DeckUpdateDto {
    name?: string | null;
    format?: string | null;
    owner?: string | null;
}

export interface Hand {
    id?: number;
    card_int_ids?: number[] | null;
    size?: number;
    hash64?: number;
    canonical_key?: string | null;
    created_at?: string;
    hand_evals?: HandEval[] | null;
}

export interface HandCreateDto {
    card_int_ids?: number[] | null;
    size?: number;
}

export interface HandEval {
    id?: number;
    hand1_id?: number;
    hand2_id?: number;
    preferred_hand?: number;
    context_json?: string | null;
    created_at?: string;
    hand1?: Hand;
    hand2?: Hand;
}

export interface HandEvalCreateDto {
    hand1_id?: number;
    hand2_id?: number;
    preferred_hand?: number;
    context_json?: string | null;
}

export interface ImportResult {
    success?: boolean;
    message?: string | null;
    cards_processed?: number;
    duration?: TimeSpan;
    is_update?: boolean;
}

export interface TimeSpan {
    ticks?: number;
    readonly days?: number;
    readonly hours?: number;
    readonly milliseconds?: number;
    readonly microseconds?: number;
    readonly nanoseconds?: number;
    readonly minutes?: number;
    readonly seconds?: number;
    readonly total_days?: number;
    readonly total_hours?: number;
    readonly total_milliseconds?: number;
    readonly total_microseconds?: number;
    readonly total_nanoseconds?: number;
    readonly total_minutes?: number;
    readonly total_seconds?: number;
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, headers, null);
}