// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgMullagain.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MtgMullagain.Infrastructure.Migrations
{
    [DbContext(typeof(MtgMullagainDbContext))]
    [Migration("20251011055810_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MtgMullagain.Core.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Cmc")
                        .HasColumnType("integer");

                    b.Property<string[]>("Colors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OracleText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PowerToughness")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Cmc")
                        .HasDatabaseName("IX_Cards_Cmc");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Cards_Name");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Cards_Type");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.CardIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique()
                        .HasDatabaseName("IX_CardIndexes_CardId");

                    b.ToTable("CardIndexes");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Deck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Owner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Format")
                        .HasDatabaseName("IX_Decks_Format");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Decks_Name");

                    b.HasIndex("Owner")
                        .HasDatabaseName("IX_Decks_Owner");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.DeckCard", b =>
                {
                    b.Property<long>("DeckId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("DeckId", "CardId");

                    b.HasIndex("CardId");

                    b.ToTable("DeckCards");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Hand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CanonicalKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int[]>("CardIntIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("Hash64")
                        .HasColumnType("bigint");

                    b.Property<short>("Size")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CardIntIds")
                        .HasDatabaseName("IX_Hands_CardIntIds_GIN");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CardIntIds"), "gin");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Hands_CreatedAt");

                    b.HasIndex("Hash64")
                        .HasDatabaseName("IX_Hands_Hash64");

                    b.HasIndex("Hash64", "Size", "CardIntIds")
                        .IsUnique()
                        .HasDatabaseName("IX_Hands_Hash64_Size_CardIntIds_Unique");

                    b.ToTable("Hands");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.HandEval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("Hand1Id")
                        .HasColumnType("bigint");

                    b.Property<long>("Hand2Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("HandId")
                        .HasColumnType("bigint");

                    b.Property<int>("PreferredHand")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HandEvals_CreatedAt");

                    b.HasIndex("Hand1Id")
                        .HasDatabaseName("IX_HandEvals_Hand1Id");

                    b.HasIndex("Hand2Id")
                        .HasDatabaseName("IX_HandEvals_Hand2Id");

                    b.HasIndex("HandId");

                    b.HasIndex("PreferredHand")
                        .HasDatabaseName("IX_HandEvals_PreferredHand");

                    b.ToTable("HandEvals");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.CardIndex", b =>
                {
                    b.HasOne("MtgMullagain.Core.Entities.Card", "Card")
                        .WithOne("CardIndex")
                        .HasForeignKey("MtgMullagain.Core.Entities.CardIndex", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.DeckCard", b =>
                {
                    b.HasOne("MtgMullagain.Core.Entities.Card", "Card")
                        .WithMany("DeckCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtgMullagain.Core.Entities.Deck", "Deck")
                        .WithMany("DeckCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.HandEval", b =>
                {
                    b.HasOne("MtgMullagain.Core.Entities.Hand", "Hand1")
                        .WithMany()
                        .HasForeignKey("Hand1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtgMullagain.Core.Entities.Hand", "Hand2")
                        .WithMany()
                        .HasForeignKey("Hand2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtgMullagain.Core.Entities.Hand", null)
                        .WithMany("HandEvals")
                        .HasForeignKey("HandId");

                    b.Navigation("Hand1");

                    b.Navigation("Hand2");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Card", b =>
                {
                    b.Navigation("CardIndex");

                    b.Navigation("DeckCards");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Deck", b =>
                {
                    b.Navigation("DeckCards");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Hand", b =>
                {
                    b.Navigation("HandEvals");
                });
#pragma warning restore 612, 618
        }
    }
}
