// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgMullagain.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MtgMullagain.Infrastructure.Migrations
{
    [DbContext(typeof(MtgMullagainDbContext))]
    [Migration("20251017184032_ConvertToSnakeCase")]
    partial class ConvertToSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MtgMullagain.Core.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cmc")
                        .HasColumnType("integer")
                        .HasColumnName("cmc");

                    b.Property<string[]>("Colors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("colors");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mana_cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OracleText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("oracle_text");

                    b.Property<string>("PowerToughness")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("power_toughness");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("p_k_cards");

                    b.HasIndex("Cmc")
                        .HasDatabaseName("IX_Cards_Cmc");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Cards_Name");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Cards_Type");

                    b.ToTable("cards");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.CardIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("p_k_card_indexes");

                    b.HasIndex("CardId")
                        .IsUnique()
                        .HasDatabaseName("IX_CardIndexes_CardId");

                    b.ToTable("card_indexes");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Deck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("format");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Owner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("p_k_decks");

                    b.HasIndex("Format")
                        .HasDatabaseName("IX_Decks_Format");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Decks_Name");

                    b.HasIndex("Owner")
                        .HasDatabaseName("IX_Decks_Owner");

                    b.ToTable("decks");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.DeckCard", b =>
                {
                    b.Property<long>("DeckId")
                        .HasColumnType("bigint")
                        .HasColumnName("deck_id");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("DeckId", "CardId");

                    b.HasIndex("CardId");

                    b.ToTable("deck_cards");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Hand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CanonicalKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("canonical_key");

                    b.Property<int[]>("CardIntIds")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("card_int_ids");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("Hash64")
                        .HasColumnType("bigint")
                        .HasColumnName("hash64");

                    b.Property<short>("Size")
                        .HasColumnType("smallint")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("p_k_hands");

                    b.HasIndex("CardIntIds")
                        .HasDatabaseName("IX_Hands_CardIntIds_GIN");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CardIntIds"), "gin");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Hands_CreatedAt");

                    b.HasIndex("Hash64")
                        .HasDatabaseName("IX_Hands_Hash64");

                    b.HasIndex("Hash64", "Size", "CardIntIds")
                        .IsUnique()
                        .HasDatabaseName("IX_Hands_Hash64_Size_CardIntIds_Unique");

                    b.ToTable("hands");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.HandEval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("context_json");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long>("Hand1Id")
                        .HasColumnType("bigint")
                        .HasColumnName("hand1_id");

                    b.Property<long>("Hand2Id")
                        .HasColumnType("bigint")
                        .HasColumnName("hand2_id");

                    b.Property<long?>("HandId")
                        .HasColumnType("bigint");

                    b.Property<int>("PreferredHand")
                        .HasColumnType("integer")
                        .HasColumnName("preferred_hand");

                    b.HasKey("Id")
                        .HasName("p_k_hand_evals");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HandEvals_CreatedAt");

                    b.HasIndex("Hand1Id")
                        .HasDatabaseName("IX_HandEvals_Hand1Id");

                    b.HasIndex("Hand2Id")
                        .HasDatabaseName("IX_HandEvals_Hand2Id");

                    b.HasIndex("HandId");

                    b.HasIndex("PreferredHand")
                        .HasDatabaseName("IX_HandEvals_PreferredHand");

                    b.ToTable("hand_evals");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.ImportMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DownloadUri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("download_uri");

                    b.Property<DateTime>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_import_metadata");

                    b.HasIndex("ImportedAt")
                        .HasDatabaseName("IX_ImportMetadata_ImportedAt");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_ImportMetadata_Type");

                    b.ToTable("import_metadata");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.CardIndex", b =>
                {
                    b.HasOne("MtgMullagain.Core.Entities.Card", "Card")
                        .WithOne("CardIndex")
                        .HasForeignKey("MtgMullagain.Core.Entities.CardIndex", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_card_indexes_cards_card_id");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.DeckCard", b =>
                {
                    b.HasOne("MtgMullagain.Core.Entities.Card", "Card")
                        .WithMany("DeckCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_deck_cards_cards_card_id");

                    b.HasOne("MtgMullagain.Core.Entities.Deck", "Deck")
                        .WithMany("DeckCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_deck_cards_decks_deck_id");

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.HandEval", b =>
                {
                    b.HasOne("MtgMullagain.Core.Entities.Hand", "Hand1")
                        .WithMany()
                        .HasForeignKey("Hand1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtgMullagain.Core.Entities.Hand", "Hand2")
                        .WithMany()
                        .HasForeignKey("Hand2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtgMullagain.Core.Entities.Hand", null)
                        .WithMany("HandEvals")
                        .HasForeignKey("HandId");

                    b.Navigation("Hand1");

                    b.Navigation("Hand2");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Card", b =>
                {
                    b.Navigation("CardIndex");

                    b.Navigation("DeckCards");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Deck", b =>
                {
                    b.Navigation("DeckCards");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Hand", b =>
                {
                    b.Navigation("HandEvals");
                });
#pragma warning restore 612, 618
        }
    }
}
