// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtgMullagain.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MtgMullagain.Infrastructure.Migrations
{
    [DbContext(typeof(MtgMullagainDbContext))]
    [Migration("20241201000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MtgMullagain.Core.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Cmc")
                        .HasColumnType("integer");

                    b.Property<string[]>("Colors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ManaCost")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OracleText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PowerToughness")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Cards_Name");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Cards_Type");

                    b.HasIndex("Cmc")
                        .HasDatabaseName("IX_Cards_Cmc");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.CardEmbedding", b =>
                {
                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<float[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(256)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("CardId");

                    b.HasIndex("ModelVersion")
                        .HasDatabaseName("IX_CardEmbeddings_ModelVersion");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CardEmbeddings_CreatedAt");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("IX_CardEmbeddings_Embedding_IVFFlat")
                        .HasAnnotation("Npgsql:IndexMethod", "ivfflat")
                        .HasAnnotation("Npgsql:IndexOperators", "vector_cosine_ops");

                    b.ToTable("CardEmbeddings");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.CardIndex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique()
                        .HasDatabaseName("IX_CardIndexes_CardId");

                    b.ToTable("CardIndexes");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Owner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Decks_Name");

                    b.HasIndex("Format")
                        .HasDatabaseName("IX_Decks_Format");

                    b.HasIndex("Owner")
                        .HasDatabaseName("IX_Decks_Owner");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.DeckCard", b =>
                {
                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("DeckId", "CardId");

                    b.HasIndex("CardId");

                    b.ToTable("DeckCards");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Hand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int[]>("CardIntIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DeckId")
                        .HasColumnType("integer");

                    b.Property<long>("Hash64")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Hash64")
                        .HasDatabaseName("IX_Hands_Hash64");

                    b.HasIndex("DeckId")
                        .HasDatabaseName("IX_Hands_DeckId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Hands_CreatedAt");

                    b.HasIndex("CardIntIds")
                        .HasDatabaseName("IX_Hands_CardIntIds_GIN")
                        .HasAnnotation("Npgsql:IndexMethod", "gin");

                    b.ToTable("Hands");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.HandEmbedding", b =>
                {
                    b.Property<int>("HandId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<float[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(256)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("HandId");

                    b.HasIndex("ModelVersion")
                        .HasDatabaseName("IX_HandEmbeddings_ModelVersion");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HandEmbeddings_CreatedAt");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("IX_HandEmbeddings_Embedding_IVFFlat")
                        .HasAnnotation("Npgsql:IndexMethod", "ivfflat")
                        .HasAnnotation("Npgsql:IndexOperators", "vector_cosine_ops");

                    b.ToTable("HandEmbeddings");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.HandEval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Hand1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Hand2Id")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredHand")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Hand1Id")
                        .HasDatabaseName("IX_HandEvals_Hand1Id");

                    b.HasIndex("Hand2Id")
                        .HasDatabaseName("IX_HandEvals_Hand2Id");

                    b.HasIndex("PreferredHand")
                        .HasDatabaseName("IX_HandEvals_PreferredHand");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HandEvals_CreatedAt");

                    b.ToTable("HandEvals");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.CardEmbedding", b =>
                {
                    b.HasOne("MtgMullagain.Core.Entities.Card", "Card")
                        .WithOne("CardEmbedding")
                        .HasForeignKey("MtgMullagain.Core.Entities.CardEmbedding", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.CardIndex", b =>
                {
                    b.HasOne("MtgMullagain.Core.Entities.Card", "Card")
                        .WithOne("CardIndex")
                        .HasForeignKey("MtgMullagain.Core.Entities.CardIndex", "CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.DeckCard", b =>
                {
                    b.HasOne("MtgMullagain.Core.Entities.Card", "Card")
                        .WithMany("DeckCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtgMullagain.Core.Entities.Deck", "Deck")
                        .WithMany("DeckCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Hand", b =>
                {
                    b.HasOne("MtgMullagain.Core.Entities.Deck", "Deck")
                        .WithMany("Hands")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.HandEmbedding", b =>
                {
                    b.HasOne("MtgMullagain.Core.Entities.Hand", "Hand")
                        .WithOne("HandEmbedding")
                        .HasForeignKey("MtgMullagain.Core.Entities.HandEmbedding", "HandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hand");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.HandEval", b =>
                {
                    b.HasOne("MtgMullagain.Core.Entities.Hand", "Hand1")
                        .WithMany()
                        .HasForeignKey("Hand1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MtgMullagain.Core.Entities.Hand", "Hand2")
                        .WithMany()
                        .HasForeignKey("Hand2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hand1");

                    b.Navigation("Hand2");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Card", b =>
                {
                    b.Navigation("CardEmbedding");

                    b.Navigation("CardIndex");

                    b.Navigation("DeckCards");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Deck", b =>
                {
                    b.Navigation("DeckCards");

                    b.Navigation("Hands");
                });

            modelBuilder.Entity("MtgMullagain.Core.Entities.Hand", b =>
                {
                    b.Navigation("HandEmbedding");
                });
#pragma warning restore 612, 618
        }
    }
}

